### ISSUE TITLE
SPDX JSON validation fails

### ISSUE THREAD

**Issue by nodeax** [anthonyharrison/sbom4files#6]
SPDX json validation fails on SBOM created using sbom4files

Source scanned: https://github.com/FreeRTOS/FreeRTOS-Kernel/releases/download/V11.1.0/FreeRTOS-KernelV11.1.0.zip

```
$ sbom4files -V
0.4.3
$ sbom4files -d ~/Downloads/FreeRTOS-Kernel-11.1.0/ -p FreeRTOS -r --sbom spdx --format json --o freertos.spdx
$ java -jar tools-java-1.1.8-jar-with-dependencies.jar Verify freertos.spdx
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
Analysis exception processing SPDX file: The SPDX Document Namespace must be set before
 other SPDX document properties are set.

```
[freertos-spdx.json](https://github.com/user-attachments/files/17034884/freertos-spdx.json)

Also fails on the online validator:
https://tools.spdx.org/app/validate/
![image](https://github.com/user-attachments/assets/1d65167c-417b-473f-ab05-76c6753c416d)

**Comment by anthonyharrison** [comment]
Issue is with Lib4SBOM - see [51](https://github.com/anthonyharrison/lib4sbom/issues/51)
